name: Action to update images

on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '5 4 * * *' # Daily at 4:05

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
    - name: Run script
      run: |
        pipenv run python covidtracking.py
    - name: Update images
      uses: stefanzweifel/git-auto-commit-action@v4.2.0
      with:
        commit_message: Update images

